AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos-lf2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ../../Lambda_Functions/search-photos
      Description: 'Lambda function for smart-photos-album searching photos'
      MemorySize: 128
      Timeout: 180
      Role: 'arn:aws:iam::913702959248:role/service-role/search-photos-role-zhg6z139'
      Environment:
        Variables:
          REGION: us-west-2
  indexPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-lf1
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ../../Lambda_Functions/index-photos
      Description: 'Lambda function for smart-photos-album indexing photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::913702959248:role/service-role/index-photos-role-85ydo69bc'
      Environment:
        Variables:
          REGION: us-west-2
    Bucket1:
      Type: 'AWS::S3::Bucket'
